### ISSUE TITLE
Code for FC version 4

### ISSUE THREAD

**Issue by morninger** [fmWebViewerWorkingGroup/fmBridgit#1]
Hi, Peter

I noticed that you used FC 3 in your examples.
If you want me to upload some sample code that works with v4 (they changed a lot of things, actually), I'll be glad to.
Ric

**Comment by PeterWagemans** [comment]
Good Morning Riccardo :-)
I've invited you to the team, If I'm not mistaking, this would allow yout to add to the repository. Feel free to add a folder with your fullcalendar v4 example using your own best judgement on how to organise your contribution. I know you, so I trust you :-)
Very happy to see this first contribution!

**Comment by PeterWagemans** [comment]
Thanks for uploading!
